name: Trigger in sequence

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟触发一次

env:
  BRANCH: main
  WAIT_TIME: 90
  POLL_INTERVAL: 10

jobs:
  trigger_workflows_in_sequence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Define function to trigger workflows
        id: define-trigger-function
        run: |
          function trigger_and_verify {
            workflow_id=$1
            echo "Triggering workflow: $workflow_id"

            # Trigger the workflow
            response=$(curl -X POST -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/dispatches" \
              -d "{\"ref\":\"${BRANCH}\"}")
            echo "Trigger response: $response"

            # Poll for workflow completion
            while true; do
              status=$(curl -s -H "Authorization: token $TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs?workflow_id=$workflow_id&status=completed&branch=${BRANCH}" \
                | jq -r '.workflow_runs[0].conclusion')

              if [[ "$status" == "success" ]]; then
                echo "Workflow $workflow_id completed successfully."
                break
              elif [[ "$status" == "failure" ]]; then
                echo "Workflow $workflow_id failed."
                exit 1
              else
                echo "Waiting for workflow $workflow_id to complete..."
                sleep $POLL_INTERVAL
              fi
            done
          }

      - name: Trigger YAML Workflow
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          source <(cat $GITHUB_ENV)
          trigger_and_verify "Run_AdBlock_Rule_Generator_YAML.yml"
          sleep $WAIT_TIME

      - name: Trigger TXT Workflow
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          source <(cat $GITHUB_ENV)
          trigger_and_verify "Run_AdBlock_Rule_Generator_TXT.yml"
          sleep $WAIT_TIME

      - name: Trigger YAML to MRS Workflow
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          source <(cat $GITHUB_ENV)
          trigger_and_verify "Convert_Ruleset_YAML_to_MRS.yml"
          sleep $WAIT_TIME

      - name: Trigger Release Workflow
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          source <(cat $GITHUB_ENV)
          trigger_and_verify "Release_ADblock_file.yml"
